# CongBao.github.io

# Site settings
title: B.C. Personal Studio
header-img: img/home-bg.jpg
description: "A studio to show my personal projects and experience sharing."
url: https://congbao.github.io/
baseurl: ""

author: Cong Bao
email: bao_cong@outlook.com
twitter_username: baocong96
github_username: CongBao
facebook_username: Cong Bao
email_username: bao_cong@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]